version: '3'

networks:
  default:
    external:
      name: tamperehacklab

services:
  matrix_bot:
    container_name: matrixbot
    image: 'matrixbot:latest'
    build: '.'
    deploy:
      restart_policy:
        condition: always
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - default
    environment:
      - MATRIX_USERNAME
      - MATRIX_PASSWORD
      - MATRIX_SERVER
      - TU_APIKEY
      - TU_CALENDARS
